### ISSUE TITLE
Docs clarification

### ISSUE THREAD

**Issue by joobei** [pcooksey/bibtex-js#14]
I like to keep all my bibtex entries on a large file. Is it possible to render a single item based on its bibtex key? Something like:

`<bibtex src="mybibfile.bib"></bibtex>`
`<div id="bibtex_display" key="knuth1890math"></div>`

**Comment by pcooksey** [comment]
There was no way of displaying only a single bibtex entry. It seems like an overkill to load the entire bibtex file to only display a single entry, but then again it is easier to keep them all in one file. 
Please checkout this [branch](../tree/limitBibtexDisplay) where I implemented the functionality. 

```
<bibtex src="mybibfile.bib"></bibtex>
<div id="bibtex_display" bibtexkeys="knuth1890math"></div>
```
Bibtexkeys uses regex so you can have multiple entries displayed if you'd like too.

`<div id="bibtex_display" bibtexkeys="knuth1890math|key2|key3"></div>`

**Comment by joobei** [comment]
Thank you for the great support! :)
It works but only for the first 
`<div id="bibtex_display"...`
If I try to print another entry further down the page it does not render.

**Comment by pcooksey** [comment]
No problem! =) 
That makes sense because the original use case for bibtex_js was to have one list of bibtex entries for the entire webpage. I didn't even think to look at that part of the code since I just thought you were trying to display a few entries on the page. 
But it is possible if I loop over the bibtex_displays, however, you'll have to change your html code some what by using `class` instead of `id`. As `id` is reserved for unique identifiers.
```
<bibtex src="mybibfile.bib"></bibtex>
<div class="bibtex_display" bibtexkeys="knuth1890math"></div>
<div class="bibtex_display" bibtexkeys="key2"></div>
```
I have updated the same [branch](../tree/limitBibtexDisplay).

**Comment by pcooksey** [comment]
[Updated documentation](https://github.com/pcooksey/bibtex-js/wiki) in the wiki that explains selecting a few bibtex entries for display.
