### ISSUE TITLE
Normalize names

### ISSUE THREAD

**Issue by tobiasdiez** [pcooksey/bibtex-js#18]
It would be nice to normalize names so that all the (valid) inputs `Philip Cooksey`, `Cooksey, Philip`, `P. Cooksey` and `Cooksey, P.` result in the same output `P. Cooksay`.

**Comment by pcooksey** [comment]
I've added the ability to normalize the output of the author names. This obviously comes at a price in execution time since bibtex_js must process every name in the various forms bibtex accepts. 
Commit: 55ab547aef15b02cbd6aaffd27f19acefb080075

Wiki page detailing usage: [Formatting authors](https://github.com/pcooksey/bibtex-js/wiki/Formatting-Authors#customized-formatting-for-authors).
