### ISSUE TITLE
problems with src and local bib

### ISSUE THREAD

**Issue by imanoles** [pcooksey/bibtex-js#41]
I have two files in the same folder: index.html and CoolPropBibTeXLibrary.bib (the same file you used in examples).

If the code of index.html is

```
<!DOCTYPE html>
<html>
<head>
	<script type="text/javascript" src="https://cdn.rawgit.com/pcooksey/bibtex-js/ef59e62c/src/bibtex_js.js"></script>
	<bibtex src="https://raw.githubusercontent.com/CoolProp/CoolProp/master/CoolPropBibTeXLibrary.bib"></bibtex>
</head>
<body>
<div id="bibtex_display">
</body>
</html>
```

it works perfectly well, but if I just change the src to **src="CoolPropBibTeXLibrary.bib"** it doesn't work.

The wrong index.html code is:

```
<!DOCTYPE html>
<html>
<head>
	<script type="text/javascript" src="https://cdn.rawgit.com/pcooksey/bibtex-js/ef59e62c/src/bibtex_js.js"></script>
	<bibtex src="CoolPropBibTeXLibrary.bib"></bibtex>
</head>
<body>
<div id="bibtex_display">
</body>
</html>
```

¿How can I do to work with local bib files? ¿What's wrong?

**Comment by pcooksey** [comment]
Are you providing the local file through a web server? If you are just working with the file on your computer without a server then the problem is probably due to cross origin requests which are not allowed by most browsers.

You can quickly fix this by make that folder into a web server by running `python -m SimpleHTTPServer` in the folder (assuming you have python installed). 
Then go to: `http://localhost:8000/folder/folder2/index.html` in your browser.

Hopefully that helps.

**Comment by imanoles** [comment]
Thanks, that's it
