### ISSUE TITLE
Limit the number of entries displayed

### ISSUE THREAD

**Issue by filiatra** [pcooksey/bibtex-js#49]
Hi,

I am thinking to display the first 10 entries on the bib file, then be able to extend the list with a "See all" button. Would that be possible ?
thnx

**Comment by pcooksey** [comment]
Right now, there isn't a way of displaying only a set number while keeping the rest hidden. 

A hack would be to do something like this:
```html
<script>
  var displayed = -1; // The script will be executed once for the
  // template so don't count it
  function displayOnly(num, element){
    if (displayed > -1 && num <= displayed) {
      element.style.display = "none";
    }
    displayed++;
  }
  function displayAll(){
    var bibtexEntries = document.querySelectorAll(".bibtexentry");
    for (var i = 0; i < bibtexEntries.length; ++i) {
      bibtexEntries[i].style.display = "block";
    }
  }				 
</script>

<div id="bibtex_display">
  <div class="bibtex_template" style="display: none;">
    <!-- Put your bibtex template in here -->
    <!-- Below: this iframe should load each time a new bibtex entry is added -->
    <iframe onload="var divTemplate = this.parentElement;displayOnly(10, divTemplate);" hidden>
    </iframe>
  </div>
</div>
<button onclick="displayAll()">See All</button> <!-- button to show all -->
```
Basically, the iframe onload function is called each time a bibtex entry is added to the webpage. We just get the parent element which is the bibtexentry and hide it if there has already been 10 bibtex entries displayed

I haven't tested this hack thoroughly and it would not work if you are planning on using a bibtex_structure since the structure elements would not be hidden.

**Comment by filiatra** [comment]
thank you for the reply, I will test it!

**Comment by pcooksey** [comment]
Okay, I am working on a better solution. The iframes is just a terrible way to implement a callback function so I am actually implementing the option to have a custom callback function that is executed each time a bibtex entry is displayed. I can already see an improvement the visual performance since the iframes were slow to load and therefore you could see all the bibtex entries and then they finally disappear once the iframe "loaded" function is executed (which isn't ideal).

**Comment by pcooksey** [comment]
Alright with commit 8c78c995accb5ee1c0c8ae07bf93eea0b408401e there is the option to add callback functions for when bibtex_js finishes processing and, more importantly for your case, when each bibtex entry is added to the webpage. So, rather than use the hackish iframe, we can use `callback="displayOnly(10, bibtexentry);"` and just hide any bibtex entry that is processed after we have counted 10 of them. Below is the code:
```html
<script>
     var displayed = 0;
     function displayOnly(num, element){
	 if (displayed > -1 && num <= displayed) {
	     element.style.display = "none";
	 }
	 displayed++;
     }
     function displayAll(bibtex){
	 var bibtexEntries = document.querySelectorAll(".bibtexentry");
	 for (var i = 0; i < bibtexEntries.length; ++i) {
	     bibtexEntries[i].style.display = "block";
	 }
     }				 
</script>

<div id="bibtex_display">
  <div class="bibtex_template" style="display: none;" callback="displayOnly(10, bibtexentry);">
  <!-- Put your template in here for however you want to format the bibtex entries -->
  </div>
</div>
<button onclick="displayAll()">See All</button>
```
Reopen the issue if you have any problems with this solution.

**Comment by illywo** [comment]
Hi there. Thank you for your solution. It works for me. However, it only limits the number of displayed entries for all displayed items. Any kind of grouping leads to an unintended behavior since only the complete list consisting of all groups is limited.

Is there any way of applying the specified limit to each group? For example, if grouped by years, limit each year to the first »i« items.

Also, with respect to the "academic style", this solution does not work for me. If the structure is grouped in sections of, for example,

```
<div class="section  @book">...</div>
<div class="section  @article">...</div>
<div class="section  @inproceedings">...</div>,
```
no item is displayed at all. My intension was to limit the display to the first »i« items of book section. Then the first »i« items of the article section and to on...

Cheers

**Comment by pcooksey** [comment]
I'm reopening this to keep track of this issue. I'll comment back once I've looked more into this. Thanks!

**Comment by pcooksey** [comment]
I'll need to look more into grouping. The way it is currently done the callback doesn't have any information on the current group. This means I don't think it can limit based on group with its current capabilities. 

In regards to the "academic style", the format has slightly changed. You no longer put the `@` before the section type so that is probably why nothing was showing up.

For limiting the display within the "academic style", you can use the following callback:
```html
<script>
      var displayed = new Map();
      function displayOnly(num, element){
          var group = element.closest(".section");
          var groupVal = group.getElementsByTagName("h1")[0].innerText;
	  if (!displayed.has(groupVal)) {
              displayed.set(groupVal, {val: 1});
          } else if (displayed.get(groupVal).val >= num) {
	      element.style.display = "none";
	  } else {
              displayed.get(groupVal).val++;
          }
      }			 
</script>

<div class="bibtex_structure">
  <div class="sections bibtextypekey">
    <div class="section article">
      <h1>Refereed Articles</h1>
        ...
    </div>
    <div class="section book">
      <h1>Books</h1>
        ...
    </div>
    <div class="section inproceedings">
      <h1>Conference and Workshop Papers</h1>
        ...
    </div>
    <div class="section misc|phdthesis|mastersthesis|bachelorsthesis|techreport">
      <h1>Other Publications</h1>
        ...
  </div>
</div>

<div class="bibtex_display">
    <div class="bibtex_template" callback="displayOnly(1,bibtexentry)">
       ...
    </div>
</div>
```
The academic style does have group information built in so we can build a callback function that limits based on sections.

**Comment by illywo** [comment]
Thanks a lot for the clarification. I could get the academic style layout to work. Also, your hack for limiting the displayed entry did work like a charm. 

In addition to this I tried to implement a button that shows all entries on click. Since I'm no web developer I couldn't get this to work. Would you think this is possible?

Cheers

**Comment by pcooksey** [comment]
Great!

Hmm, did you try my solution from above?
```html
<script>
function displayAll(bibtex){
  var bibtexEntries = document.querySelectorAll(".bibtexentry");
  for (var i = 0; i < bibtexEntries.length; ++i) {
	     bibtexEntries[i].style.display = "block";
	 }
}	
</script>
<button onclick="displayAll()">See All</button>
```
It works on my example test page.

**Comment by illywo** [comment]
Thanks again for you help. I tried something similar. For the sake of testing i just called `displayOnly()` again with a very large number of entries. It seems i gave up too quickly, your solution works like a charm. Consider my question answered :grinning:.

Cheers
